services:
  - docker:18-dind

variables:
  GITHUB_REF: $CI_COMMIT_SHA

stages:
  - build
  - publish

build:
  image: registry.gitlab.com/tokend/deployment/docker-build:latest
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - tokend
  script:
    - .ci/build.sh

lint:
  image: registry.gitlab.com/tokend/deployment/js-build:latest
  stage: build
  tags:
    - tokend
  script:
    - .ci/lint.sh

unit_test:
  image: registry.gitlab.com/tokend/deployment/js-build:latest
  stage: build
  tags:
    - tokend
  script:
    - .ci/test.sh

publish:
  image: registry.gitlab.com/tokend/deployment/docker-build:latest
  stage: publish
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - tokend
  only:
    - /^.+\..+\..+$/
  script:
    - .ci/publish.sh
